name: "CI"
on:
  push:
    branches:
      - "main"
env:
  NODE_VERSION: "22"
  SPIN_VERSION: ""
jobs:
  spin:
    runs-on: "ubuntu-latest"
    name: Build Spin App
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          plugins: js2wasm
      - name: Component Dependency Installation
        run: npm install
        working-directory: .
      - name: Build eleventy-website
        run: spin build
        working-directory: .
      - name: Build and deploy
            uses: fermyon/actions/spin/deploy@v1
            with:
            fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}